name: "Write new article with Sycophant"
on:
  schedule:
    # Run every 10 days at 07:00AM GMT+2
    - cron: "0 5 */10 * *"

  # Run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  generate_article:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout robots.army
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}
      - name: Checkout platisd/sycophant
        uses: actions/checkout@v3
        with:
          repository: platisd/sycophant
          path: sycophant
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install sycophant's dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r sycophant/requirements.txt
      - name: Generate article with sycophant
        run: |
          # Install robots.army Python dependencies
          pip install -r utils/requirements.txt
          # Get a random author from the author's list
          export RANDOM_AUTHOR=$(python utils/get_random_author.py _data/authors.yml)
          python sycophant/sycophant.py \
            --openai-api-key ${{ secrets.OPENAI_API_KEY }} \
            --news-api-key ${{ secrets.NEWS_API_KEY }} \
            --config sycophant-config.yml \
            --additional-render-args "{\"post_author\": \"$RANDOM_AUTHOR\"}"
      - name: Commit and push changes
        run: |
          git config --global user.name "Sycophant"
          git config --global user.email "platisd@users.noreply.github.com"
          git add _posts assets
          current_date=$(date -u +"%Y-%m-%d %H:%M:%S")
          git commit -m "Publish article at $current_date"
          git push origin master
