name: "Write article when maintainer creates issue"
on: 
  issues:
    types: [opened, reopened]

jobs:
  write-article:
    if: github.event.issue.user.login == github.repository_owner && startsWith(github.event.issue.title, 'Write new article')
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      issues: write
    steps:
      - name: Checkout robots.army
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}
      - name: Checkout platisd/sycophant
        uses: actions/checkout@v3
        with:
          repository: platisd/sycophant
          path: sycophant
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install sycophant's dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r sycophant/requirements.txt
      - name: Write article with sycophant
        run: |
          # Install robots.army Python dependencies
          pip install -r utils/requirements.txt
          # Get a random author from the author's list
          export RANDOM_AUTHOR=$(python utils/get_random_author.py _data/authors.yml)
          provided_links="${{ github.event.issue.body }}"
          set +e
          python sycophant/sycophant.py \
            --openai-api-key ${{ secrets.OPENAI_API_KEY }} \
            --news-api-key ${{ secrets.NEWS_API_KEY }} \
            --config sycophant-config.yml \
            --links "$provided_links" \
            --additional-render-args "{\"post_author\": \"$RANDOM_AUTHOR\"}"
          result=$?
          if [ $result -ne 0 ]; then
            GITHUB_WORKFLOW_URL=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
            gh issue comment "${{ github.event.issue.number }}" --body "Failed to write article, refer to the [logs]($GITHUB_WORKFLOW_URL)"
            exit $result
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit and push changes
        run: |
          git config --global user.name "Sycophant"
          git config --global user.email "platisd@users.noreply.github.com"
          git add _posts assets
          current_date=$(date -u +"%Y-%m-%d %H:%M:%S")
          git commit -m "Wrote article, on demand, at $current_date"
          git push origin master
          gh issue close --comment "Wrote new article, go to [robots.army](https://robots.army)" "${{ github.event.issue.number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  illegal-write:
    if: github.event.issue.user.login != github.repository_owner && startsWith(github.event.issue.title, 'Write new article')
    runs-on: ubuntu-22.04
    permissions:
      issues: write
    steps:
      - name: Checkout robots.army
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Close and comment on issue
        run: |
          gh issue close --comment "Only @${{ github.repository_owner }} can request to write an article" "${{ github.event.issue.number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
